# Copyright 2020 Nordcloud Oy or its affiliates. All Rights Reserved.

_extends: nordcloud/github-settings:.github/settings.yml
repository:
  name: "klarity-scanner-vmware-cli"
  description: "Klarity self-hosted scanner for your VMware environments"
teams:
  - name: architects
    permission: admin
