on:
  push:
    tags:
    - v*

jobs:
  release:
    name: Release klarity-scanner-vmware-cli
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make build
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelase: false
    - name: Upload asset (Windows amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/klarity-scanner-vmware-cli.exe
        asset_name: klarity-scanner-vmware-cli.exe (windows amd64)
        asset_content_type: application/binary
    - name: Upload asset (Linux amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/klarity-scanner-vmware-cli
        asset_name: klarity-scanner-vmware-cli (linux amd64)
        asset_content_type: application/binary